"""
visits/services.py
==================
Service layer for patient visit sessions.

Function index:
  initiate_visit(user, org_qr_token, data)          → PatientVisit
  end_visit(user, visit_id)                          → PatientVisit
  get_visit(user, visit_id)                          → PatientVisit
  list_patient_visits(user, patient_id)              → QuerySet[PatientVisit]
  check_practitioner_visit_access(practitioner, patient_id) → PatientVisit
  _get_or_create_visit_access(visit, practitioner)   → PatientVisitAccess
"""

import logging
from datetime import timedelta
from uuid import UUID

import jwt
from django.conf import settings
from django.db import transaction
from django.utils import timezone

from apps.patients.exceptions import AccessDenied, PatientNotFound, PatientRetracted
from apps.patients.models import Patient
from apps.patients.services import _get_active_access

from .exceptions import (
    InvalidOrgQRToken,
    OrganisationNotFound,
    VisitAlreadyActive,
    VisitAlreadyEnded,
    VisitNotFound,
    PractitionerNotAtOrg,
)
from .models import PatientVisit, PatientVisitAccess

logger = logging.getLogger(__name__)

_VISIT_DEFAULT_EXPIRY_HOURS = 24
_ORG_QR_TOKEN_TYPE          = "org_qr"


# ===========================================================================
# ORG QR TOKEN VERIFICATION
# ===========================================================================

def _verify_org_qr_token(token: str) -> UUID:
    """
    Decode and verify a signed org QR token.
    Returns the organisation_id encoded in the token.

    Org QR tokens are signed with SECRET_KEY using HS256.
    They encode:
        {
            "type":   "org_qr",
            "org_id": "<uuid>",
            "exp":    <unix timestamp>   (15 min default, set when generated)
        }

    Raises ValueError if the token is invalid, expired, or wrong type.
    """
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        raise InvalidOrgQRToken("Organisation QR code has expired. Ask reception to refresh it.")
    except jwt.InvalidTokenError:
        raise InvalidOrgQRToken("Invalid organisation QR code.")

    if payload.get("type") != _ORG_QR_TOKEN_TYPE:
        raise InvalidOrgQRToken("Invalid QR code type.")

    try:
        return UUID(payload["org_id"])
    except (KeyError, ValueError):
        raise InvalidOrgQRToken("Malformed organisation QR code.")


# ===========================================================================
# INITIATE VISIT
# ===========================================================================

@transaction.atomic
def initiate_visit(user, patient_id: UUID, org_qr_token: str, data=None) -> PatientVisit:
    """
    Patient initiates a visit by scanning an organisation's QR code.

    Steps:
      1. Verify the org QR token → extract org_id
      2. Verify patient exists and requesting user has primary/delegate access
      3. Check for an already-active visit at this org (prevent duplicates)
      4. Create PatientVisit — no PatientVisitAccess records yet (lazy)

    The QR token is a signed JWT generated by the org's QR endpoint.
    It encodes the org_id and has a short expiry (15 min).
    The patient scans it at reception.
    """
    # Verify the org QR token
    try:
        org_id = _verify_org_qr_token(org_qr_token)
    except InvalidOrgQRToken as e:
        raise e

    # Verify patient access — patient must have manage rights to initiate a visit
    # (they are presenting their own records to the org)
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied(
            "Only the primary holder or managing delegate can initiate a visit."
        )

    patient = access.patient
    if not patient.is_active:
        raise PatientRetracted()

    # Verify the organisation exists and is verified
    try:
        from django.apps import apps
        Organisation = apps.get_model("integrations", "Organisation")
        organisation = Organisation.objects.get(pk=org_id, verified=True)
    except LookupError:
        raise OrganisationNotFound("integrations app not yet configured.")
    except Organisation.DoesNotExist:
        raise OrganisationNotFound()

    # Prevent duplicate active visits at the same org
    existing = PatientVisit.objects.filter(
        patient=patient,
        organisation=organisation,
        is_active=True,
        expires_at__gt=timezone.now(),
    ).first()

    if existing:
        raise VisitAlreadyActive(
            f"You already have an active visit at this organisation "
            f"(expires {existing.expires_at.strftime('%H:%M %Z')}). "
            "End the existing visit first."
        )

    expiry_hours = _VISIT_DEFAULT_EXPIRY_HOURS
    if data and hasattr(data, "expiry_hours") and data.expiry_hours:
        expiry_hours = min(data.expiry_hours, 72)  # Hard cap: 3 days

    visit = PatientVisit.objects.create(
        patient       = patient,
        organisation  = organisation,
        initiated_by  = user,
        expires_at    = timezone.now() + timedelta(hours=expiry_hours),
        visit_reason  = getattr(data, "visit_reason", None),
    )

    logger.info(
        "Visit initiated. visit_id=%s patient_id=%s org_id=%s expiry_hours=%s",
        visit.id, patient_id, org_id, expiry_hours,
    )

    return visit


# ===========================================================================
# END VISIT
# ===========================================================================

@transaction.atomic
def end_visit(user, patient_id: UUID, visit_id: UUID) -> PatientVisit:
    """
    Patient (or org admin) ends a visit early.
    Deactivates the visit and all associated PatientVisitAccess records.
    """
    # Verify the user has manage access to this patient
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied("Only the primary holder or managing delegate can end a visit.")

    try:
        visit = PatientVisit.objects.select_for_update().get(
            id=visit_id,
            patient_id=patient_id,
        )
    except PatientVisit.DoesNotExist:
        raise VisitNotFound()

    if not visit.is_active:
        raise VisitAlreadyEnded()

    now = timezone.now()
    visit.is_active = False
    visit.ended_at  = now
    visit.ended_by  = user
    visit.save(update_fields=["is_active", "ended_at", "ended_by", "updated_at"])

    # Deactivate all practitioner visit access records derived from this visit
    PatientVisitAccess.objects.filter(
        visit=visit,
        is_active=True,
    ).update(is_active=False, revoked_at=now)

    logger.info(
        "Visit ended. visit_id=%s patient_id=%s ended_by=%s",
        visit_id, patient_id, user.id,
    )

    return visit


# ===========================================================================
# LIST PATIENT VISITS
# ===========================================================================

def list_patient_visits(user, patient_id: UUID):
    """List all visits for a patient. Requires manage access."""
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied("Only the primary holder or managing delegate can view visits.")

    return (
        PatientVisit.objects
        .filter(patient_id=patient_id)
        .select_related("organisation")
        .order_by("-initiated_at")
    )


# ===========================================================================
# LAZY VISIT ACCESS CHECK (called by practitioner-facing endpoints)
# ===========================================================================

def check_practitioner_visit_access(practitioner, patient_id: UUID) -> PatientVisit:
    """
    Check whether a practitioner has visit-based access to a patient.

    Called by any endpoint that serves data to a practitioner during a visit.
    If the practitioner has access, creates a PatientVisitAccess record lazily
    (on first call) or updates last_accessed_at (on subsequent calls).

    Returns the active PatientVisit if access is granted.
    Raises AccessDenied if no active visit exists for this org.

    This is the core of the lazy access model:
      - No records are created at visit initiation
      - Records are created here, on first actual data access
      - The audit log reflects who actually looked at the data
    """
    # Find an active visit for this patient at the practitioner's organisation
    visit = PatientVisit.objects.filter(
        patient_id=patient_id,
        organisation=practitioner.organisation,
        is_active=True,
        expires_at__gt=timezone.now(),
    ).first()

    if not visit:
        raise PractitionerNotAtOrg()

    # Lazy create or update the visit access record
    _get_or_create_visit_access(visit, practitioner)

    return visit


def _get_or_create_visit_access(
    visit: PatientVisit,
    practitioner,
) -> PatientVisitAccess:
    """
    Get or create a PatientVisitAccess record for this (visit, practitioner) pair.

    Uses get_or_create to handle concurrent first-access requests from the
    same practitioner safely. The unique constraint on (visit, practitioner)
    prevents duplicate records even under concurrent requests.

    On subsequent calls (practitioner already has a record):
      - Updates last_accessed_at via auto_now=True on save()
      - Does not create a new record
    """
    access, created = PatientVisitAccess.objects.get_or_create(
        visit=visit,
        practitioner=practitioner,
        defaults={
            "patient":  visit.patient,
            "is_active": True,
        },
    )

    if not created:
        # Record exists — touch it to update last_accessed_at
        access.save(update_fields=["last_accessed_at"])

    if created:
        logger.info(
            "Lazy visit access created. visit_id=%s practitioner_id=%s patient_id=%s",
            visit.id, practitioner.id, visit.patient_id,
        )

    return access


# ===========================================================================
# VISIT SCOPE AND TIMELINE REQUEST SERVICES
# ===========================================================================

def get_visit_emergency_summary(practitioner, visit_id: UUID) -> dict:
    """
    Return the emergency summary (Tier 1) for a patient during a visit.
    Auto-granted — no patient approval needed.
    Available to all verified practitioners at the visiting org.

    Contains:
      - Blood group + basic demographics
      - Active allergies (HIGH criticality first — critical for safe prescribing)
      - Active medications
      - Most recent vital signs
      - Active conditions
      - Pending test orders

    Maps to FHIR IPS (International Patient Summary).
    Always available at verified organisations for patient safety.
    """
    visit = PatientVisit.objects.select_related(
        "patient", "organisation"
    ).get(pk=visit_id)

    # Verify practitioner belongs to the visiting org
    check_practitioner_visit_access(practitioner, visit.patient_id)

    patient = visit.patient

    # Import stats from medical_events — lazy import to avoid circular
    from medical_events.stats import (
        get_allergy_summary,
        get_medication_history,
        get_recent_vitals,
        get_conditions_summary,
        get_pending_orders,
    )

    allergies   = get_allergy_summary(patient.id)
    medications = get_medication_history(patient.id)
    vitals      = get_recent_vitals(patient.id, limit=1)
    conditions  = get_conditions_summary(patient.id)
    orders      = get_pending_orders(patient.id)

    return {
        "access_scope":   "emergency_summary",
        "visit_id":       str(visit_id),
        "organisation":   visit.organisation.name,
        "patient": {
            "id":          str(patient.id),
            "full_name":   patient.full_name,
            "birth_date":  str(patient.birth_date),
            "gender":      patient.gender,
            "blood_group": patient.blood_group,
            "mrn":         patient.mrn,
        },
        "allergies":            allergies,
        "active_medications":   medications["active"],
        "latest_vitals":        vitals[0] if vitals else None,
        "active_conditions":    conditions["active"],
        "pending_orders":       orders,
        "note": (
            "This is the emergency summary automatically available "
            "to verified organisations. For full timeline access, "
            "submit a VisitTimelineRequest and await patient approval."
        ),
    }


def get_visit_full_timeline(practitioner, visit_id: UUID) -> dict:
    """
    Return the full timeline for a patient during a visit.
    Requires PatientVisit.access_scope = full_timeline (patient-approved).

    Raises FullTimelineNotApproved if patient has not yet approved.
    """
    from .exceptions import FullTimelineNotApproved
    from .models import VisitAccessScope

    visit = PatientVisit.objects.select_related("patient").get(pk=visit_id)

    # Verify practitioner has visit access
    check_practitioner_visit_access(practitioner, visit.patient_id)

    if visit.access_scope != VisitAccessScope.FULL_TIMELINE:
        raise FullTimelineNotApproved()

    # Return full visible timeline via medical_events service
    from medical_events.services import get_timeline
    from medical_events.stats import get_doctor_dashboard

    # Use a system-level read — practitioner has been verified above
    # We pass the practitioner's user for audit purposes
    dashboard = get_doctor_dashboard(visit.patient_id)
    dashboard["access_scope"] = "full_timeline"
    dashboard["visit_id"]     = str(visit_id)
    dashboard["organisation"] = visit.organisation.name

    return dashboard


@transaction.atomic
def request_full_timeline(practitioner, visit_id: UUID, reason: str):
    """
    Practitioner requests full timeline access for an active visit.
    One pending request per visit allowed.
    Patient must approve before access_scope upgrades to full_timeline.
    """
    from .exceptions import TimelineRequestAlreadyExists
    from .models import VisitTimelineRequest, VisitTimelineRequestStatus, VisitAccessScope

    visit = PatientVisit.objects.select_for_update().select_related(
        "patient"
    ).get(pk=visit_id)

    # Verify practitioner has visit access
    check_practitioner_visit_access(practitioner, visit.patient_id)

    # Already has full access — no need to request
    if visit.access_scope == VisitAccessScope.FULL_TIMELINE:
        from django.core.exceptions import ValidationError
        raise ValidationError({"detail": "Full timeline access is already active for this visit."})

    # Check for existing pending request
    if VisitTimelineRequest.objects.filter(
        visit=visit,
        status=VisitTimelineRequestStatus.PENDING,
    ).exists():
        raise TimelineRequestAlreadyExists()

    req = VisitTimelineRequest.objects.create(
        visit        = visit,
        patient      = visit.patient,
        requested_by = practitioner,
        reason       = reason,
    )

    logger.info(
        "Full timeline requested. visit_id=%s practitioner=%s patient=%s",
        visit_id, practitioner.id, visit.patient_id,
    )
    return req


@transaction.atomic
def respond_to_timeline_request(user, patient_id: UUID, request_id: UUID, approve: bool, denial_reason: str = None):
    """
    Patient approves or denies a full timeline request.
    If approved — PatientVisit.access_scope upgrades to full_timeline.
    """
    from .exceptions import TimelineRequestNotFound, TimelineRequestNotPending
    from .models import VisitTimelineRequest, VisitTimelineRequestStatus, VisitAccessScope
    from patients.services import _get_active_access
    from patients.exceptions import AccessDenied

    # Verify patient has manage access
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied("Only the primary holder or delegate can respond to timeline requests.")

    try:
        req = VisitTimelineRequest.objects.select_for_update().select_related(
            "visit"
        ).get(id=request_id, patient_id=patient_id)
    except VisitTimelineRequest.DoesNotExist:
        raise TimelineRequestNotFound()

    if req.status != VisitTimelineRequestStatus.PENDING:
        raise TimelineRequestNotPending(f"This request is already {req.status}.")

    now = timezone.now()

    if approve:
        # Upgrade visit scope
        visit = PatientVisit.objects.select_for_update().get(pk=req.visit_id)
        visit.access_scope = VisitAccessScope.FULL_TIMELINE
        visit.save(update_fields=["access_scope", "updated_at"])

        req.status       = VisitTimelineRequestStatus.APPROVED
        req.responded_at = now
        req.responded_by = user
    else:
        req.status        = VisitTimelineRequestStatus.DENIED
        req.responded_at  = now
        req.responded_by  = user
        req.denial_reason = denial_reason

    req.save(update_fields=[
        "status", "responded_at", "responded_by", "denial_reason"
    ])

    logger.info(
        "Timeline request %s. request_id=%s patient_id=%s by=%s",
        "approved" if approve else "denied",
        request_id, patient_id, user.id,
    )
    return req


def list_pending_timeline_requests(user, patient_id: UUID):
    """List all pending timeline requests for a patient to review."""
    from patients.services import _get_active_access
    from .models import VisitTimelineRequest, VisitTimelineRequestStatus

    access = _get_active_access(user, patient_id)

    return (
        VisitTimelineRequest.objects
        .filter(
            patient_id = patient_id,
            status     = VisitTimelineRequestStatus.PENDING,
        )
        .select_related("visit__organisation", "requested_by")
        .order_by("-created_at")
    )