"""
visits/services.py
==================
Service layer for patient visit sessions.

Function index:
  initiate_visit(user, org_qr_token, data)          → PatientVisit
  end_visit(user, visit_id)                          → PatientVisit
  get_visit(user, visit_id)                          → PatientVisit
  list_patient_visits(user, patient_id)              → QuerySet[PatientVisit]
  check_practitioner_visit_access(practitioner, patient_id) → PatientVisit
  _get_or_create_visit_access(visit, practitioner)   → PatientVisitAccess
"""

import logging
from datetime import timedelta
from uuid import UUID

import jwt
from django.conf import settings
from django.db import transaction
from django.utils import timezone

from apps.patients.exceptions import AccessDenied, PatientNotFound, PatientRetracted
from apps.patients.models import Patient
from apps.patients.services import _get_active_access

from .models import PatientVisit, PatientVisitAccess

logger = logging.getLogger(__name__)

_VISIT_DEFAULT_EXPIRY_HOURS = 24
_ORG_QR_TOKEN_TYPE          = "org_qr"


# ===========================================================================
# ORG QR TOKEN VERIFICATION
# ===========================================================================

def _verify_org_qr_token(token: str) -> UUID:
    """
    Decode and verify a signed org QR token.
    Returns the organisation_id encoded in the token.

    Org QR tokens are signed with SECRET_KEY using HS256.
    They encode:
        {
            "type":   "org_qr",
            "org_id": "<uuid>",
            "exp":    <unix timestamp>   (15 min default, set when generated)
        }

    Raises ValueError if the token is invalid, expired, or wrong type.
    """
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        raise ValueError("Organisation QR code has expired. Ask reception to refresh it.")
    except jwt.InvalidTokenError:
        raise ValueError("Invalid organisation QR code.")

    if payload.get("type") != _ORG_QR_TOKEN_TYPE:
        raise ValueError("Invalid QR code type.")

    try:
        return UUID(payload["org_id"])
    except (KeyError, ValueError):
        raise ValueError("Malformed organisation QR code.")


# ===========================================================================
# INITIATE VISIT
# ===========================================================================

@transaction.atomic
def initiate_visit(user, patient_id: UUID, org_qr_token: str, data=None) -> PatientVisit:
    """
    Patient initiates a visit by scanning an organisation's QR code.

    Steps:
      1. Verify the org QR token → extract org_id
      2. Verify patient exists and requesting user has primary/delegate access
      3. Check for an already-active visit at this org (prevent duplicates)
      4. Create PatientVisit — no PatientVisitAccess records yet (lazy)

    The QR token is a signed JWT generated by the org's QR endpoint.
    It encodes the org_id and has a short expiry (15 min).
    The patient scans it at reception.
    """
    # Verify the org QR token
    try:
        org_id = _verify_org_qr_token(org_qr_token)
    except ValueError as e:
        from django.core.exceptions import ValidationError
        raise ValidationError({"org_qr_token": str(e)})

    # Verify patient access — patient must have manage rights to initiate a visit
    # (they are presenting their own records to the org)
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied(
            "Only the primary holder or managing delegate can initiate a visit."
        )

    patient = access.patient
    if not patient.is_active:
        raise PatientRetracted()

    # Verify the organisation exists and is verified
    try:
        from django.apps import apps
        Organisation = apps.get_model("integrations", "Organisation")
        organisation = Organisation.objects.get(pk=org_id, verified=True)
    except LookupError:
        from django.core.exceptions import ValidationError
        raise ValidationError({"org_qr_token": "integrations app not yet configured."})
    except Organisation.DoesNotExist:
        from django.core.exceptions import ValidationError
        raise ValidationError({"org_qr_token": "Organisation not found or not verified."})

    # Prevent duplicate active visits at the same org
    existing = PatientVisit.objects.filter(
        patient=patient,
        organisation=organisation,
        is_active=True,
        expires_at__gt=timezone.now(),
    ).first()

    if existing:
        from django.core.exceptions import ValidationError
        raise ValidationError({
            "detail": (
                f"You already have an active visit at this organisation "
                f"(expires {existing.expires_at.strftime('%H:%M %Z')}). "
                "End the existing visit first if you want to start a new one."
            )
        })

    expiry_hours = _VISIT_DEFAULT_EXPIRY_HOURS
    if data and hasattr(data, "expiry_hours") and data.expiry_hours:
        expiry_hours = min(data.expiry_hours, 72)  # Hard cap: 3 days

    visit = PatientVisit.objects.create(
        patient       = patient,
        organisation  = organisation,
        initiated_by  = user,
        expires_at    = timezone.now() + timedelta(hours=expiry_hours),
        visit_reason  = getattr(data, "visit_reason", None),
    )

    logger.info(
        "Visit initiated. visit_id=%s patient_id=%s org_id=%s expiry_hours=%s",
        visit.id, patient_id, org_id, expiry_hours,
    )

    return visit


# ===========================================================================
# END VISIT
# ===========================================================================

@transaction.atomic
def end_visit(user, patient_id: UUID, visit_id: UUID) -> PatientVisit:
    """
    Patient (or org admin) ends a visit early.
    Deactivates the visit and all associated PatientVisitAccess records.
    """
    # Verify the user has manage access to this patient
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied("Only the primary holder or managing delegate can end a visit.")

    try:
        visit = PatientVisit.objects.select_for_update().get(
            id=visit_id,
            patient_id=patient_id,
        )
    except PatientVisit.DoesNotExist:
        raise PatientNotFound("Visit not found.")

    if not visit.is_active:
        from django.core.exceptions import ValidationError
        raise ValidationError({"detail": "This visit has already ended."})

    now = timezone.now()
    visit.is_active = False
    visit.ended_at  = now
    visit.ended_by  = user
    visit.save(update_fields=["is_active", "ended_at", "ended_by", "updated_at"])

    # Deactivate all practitioner visit access records derived from this visit
    PatientVisitAccess.objects.filter(
        visit=visit,
        is_active=True,
    ).update(is_active=False, revoked_at=now)

    logger.info(
        "Visit ended. visit_id=%s patient_id=%s ended_by=%s",
        visit_id, patient_id, user.id,
    )

    return visit


# ===========================================================================
# LIST PATIENT VISITS
# ===========================================================================

def list_patient_visits(user, patient_id: UUID):
    """List all visits for a patient. Requires manage access."""
    access = _get_active_access(user, patient_id)
    if not access.can_manage_access:
        raise AccessDenied("Only the primary holder or managing delegate can view visits.")

    return (
        PatientVisit.objects
        .filter(patient_id=patient_id)
        .select_related("organisation")
        .order_by("-initiated_at")
    )


# ===========================================================================
# LAZY VISIT ACCESS CHECK (called by practitioner-facing endpoints)
# ===========================================================================

def check_practitioner_visit_access(practitioner, patient_id: UUID) -> PatientVisit:
    """
    Check whether a practitioner has visit-based access to a patient.

    Called by any endpoint that serves data to a practitioner during a visit.
    If the practitioner has access, creates a PatientVisitAccess record lazily
    (on first call) or updates last_accessed_at (on subsequent calls).

    Returns the active PatientVisit if access is granted.
    Raises AccessDenied if no active visit exists for this org.

    This is the core of the lazy access model:
      - No records are created at visit initiation
      - Records are created here, on first actual data access
      - The audit log reflects who actually looked at the data
    """
    # Find an active visit for this patient at the practitioner's organisation
    visit = PatientVisit.objects.filter(
        patient_id=patient_id,
        organisation=practitioner.organisation,
        is_active=True,
        expires_at__gt=timezone.now(),
    ).first()

    if not visit:
        raise AccessDenied(
            "No active visit session found for this patient at your organisation. "
            "The patient must initiate a visit by scanning your organisation's QR code."
        )

    # Lazy create or update the visit access record
    _get_or_create_visit_access(visit, practitioner)

    return visit


def _get_or_create_visit_access(
    visit: PatientVisit,
    practitioner,
) -> PatientVisitAccess:
    """
    Get or create a PatientVisitAccess record for this (visit, practitioner) pair.

    Uses get_or_create to handle concurrent first-access requests from the
    same practitioner safely. The unique constraint on (visit, practitioner)
    prevents duplicate records even under concurrent requests.

    On subsequent calls (practitioner already has a record):
      - Updates last_accessed_at via auto_now=True on save()
      - Does not create a new record
    """
    access, created = PatientVisitAccess.objects.get_or_create(
        visit=visit,
        practitioner=practitioner,
        defaults={
            "patient":  visit.patient,
            "is_active": True,
        },
    )

    if not created:
        # Record exists — touch it to update last_accessed_at
        access.save(update_fields=["last_accessed_at"])

    if created:
        logger.info(
            "Lazy visit access created. visit_id=%s practitioner_id=%s patient_id=%s",
            visit.id, practitioner.id, visit.patient_id,
        )

    return access