# Generated by Django 6.0.2 on 2026-02-19 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPatientIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(choices=[('in_abha', 'ABHA — India (Ayushman Bharat Health Account)'), ('au_ihi', 'IHI — Australia (Individual Healthcare Identifier)'), ('nz_nhi', 'NHI — New Zealand (National Health Index)'), ('uk_nhs', 'NHS Number — England / Wales / Isle of Man'), ('uk_chi', 'CHI Number — Scotland'), ('uk_hc', 'H&C Number — Northern Ireland'), ('ie_ihi', 'IHI — Ireland (Individual Health Identifier)'), ('ch_epr_spid', 'EPR-SPID — Switzerland'), ('de_kvnr', 'KVNR — Germany (Krankenversichertennummer)'), ('fr_nir', 'NIR — France (Numéro de Sécurité Sociale)'), ('nl_bsn', 'BSN — Netherlands (Burgerservicenummer)'), ('dk_cpr', 'CPR — Denmark (Civil Registration Number)'), ('se_personnummer', 'Personnummer — Sweden'), ('no_fnr', 'Fødselsnummer — Norway'), ('fi_hetu', 'Hetu — Finland (Henkilötunnus)'), ('ee_pic', 'PIC — Estonia (Personal Identification Code)'), ('sa_nhi', 'NHI — Saudi Arabia (National Health ID)'), ('ae_uhi', 'UHI — UAE (Unified Health Identifier)'), ('kr_rrn', 'RRN — South Korea (Resident Registration Number)'), ('jp_mynumber', 'My Number — Japan'), ('sg_nric', 'NRIC/FIN — Singapore'), ('ca_phn', 'PHN — Canada (Provincial Health Number)'), ('us_mrn', 'MRN — United States (Local Medical Record Number)'), ('br_cns', 'CNS — Brazil (Cartão Nacional de Saúde)'), ('za_hprs', 'HPRS — South Africa (Health Patient Registration)'), ('hospital_mrn', 'Hospital MRN (Local)'), ('insurance_id', 'Health Insurance Member ID'), ('other', 'Other / Custom')], help_text='The national/external health identity system.', max_length=32)),
                ('identity_value', models.CharField(help_text='The unique ID value within the external system.', max_length=256)),
                ('fhir_system_uri', models.CharField(blank=True, help_text='Official FHIR Identifier.system URI. Auto-populated on save.', max_length=512, null=True)),
                ('secondary_value', models.CharField(blank=True, max_length=256, null=True)),
                ('secondary_label', models.CharField(blank=True, help_text="Label for secondary_value (e.g. 'ABHA Address', 'Card Number').", max_length=64, null=True)),
                ('identity_region', models.CharField(blank=True, help_text='Regional sub-authority. Required for CA_PHN (province), AE_UHI (emirate), US_MRN (facility).', max_length=64, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(choices=[('otp', 'OTP (One-Time Password)'), ('aadhaar_otp', 'Aadhaar OTP (India — ABDM)'), ('face_auth', 'Face Authentication'), ('demographics', 'Demographic Match'), ('document_upload', 'Document Upload (Manual Review)'), ('biometric', 'Biometric Verification'), ('oauth', 'OAuth / SMART-on-FHIR'), ('manual_admin', 'Manual (Admin Verified)'), ('unverified', 'Not Yet Verified')], default='unverified', max_length=32)),
                ('is_linked', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('linking_token', models.TextField(blank=True, null=True)),
                ('linking_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, help_text='Full original API response from external identity system. Internal use only.', null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_patient_identities',
            },
        ),
    ]
