# Generated by Django 6.0.2 on 2026-02-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpatientidentity',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_identities', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='externalpatientidentity',
            index=models.Index(fields=['system', 'identity_value'], name='idx_ext_identity_system_value'),
        ),
        migrations.AddIndex(
            model_name='externalpatientidentity',
            index=models.Index(fields=['patient', 'is_linked', 'is_revoked'], name='idx_ext_identity_patient_active'),
        ),
        migrations.AddConstraint(
            model_name='externalpatientidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_revoked', False)), fields=('patient', 'system'), name='uq_patient_system_active'),
        ),
    ]
