# Generated by Django 6.0.2 on 2026-02-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalpatientidentity',
            new_name='idx_ext_pat_identity_active',
            old_name='idx_ext_identity_patient_active',
        ),
    ]
