# Generated by Django 6.0.2 on 2026-04-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_rename_idx_ext_identity_patient_active_idx_ext_pat_identity_active'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalpatientidentity',
            new_name='idx_ext_identity_patient_active',
            old_name='idx_ext_pat_identity_active',
        ),
    ]
