# Generated by Django 6.0.2 on 2026-04-05 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, help_text='National medical licence or registration number.', max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, help_text='e.g. Cardiology, General Practice, Radiology.', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='True once licence has been verified. Only verified practitioners can submit provider_verified events.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_source', models.CharField(choices=[('manual', 'Manual (Admin Verified)'), ('registry', 'National Registry Lookup'), ('national_gateway', 'National Health Gateway'), ('self_reported', 'Self-Reported (Unverified)')], default='self_reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The UHR user account for this practitioner.', on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practitioners',
            },
        ),
        migrations.CreateModel(
            name='PractitionerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(blank=True, help_text="e.g. 'Consultant Cardiologist', 'Resident', 'GP'.", max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_roles', to='organisations.organisation')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='practitioners.practitioner')),
            ],
            options={
                'db_table': 'practitioner_roles',
            },
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['is_verified'], name='idx_prac_verified'),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['license_number'], name='idx_prac_license'),
        ),
        migrations.AddIndex(
            model_name='practitionerrole',
            index=models.Index(fields=['practitioner', 'is_active'], name='idx_prac_role_active'),
        ),
        migrations.AddIndex(
            model_name='practitionerrole',
            index=models.Index(fields=['organisation', 'is_active'], name='idx_prac_role_org_active'),
        ),
    ]
