# Generated by Django 6.0.2 on 2026-04-06 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_description_organisation_parent_and_more'),
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembershipRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_role_title', models.CharField(blank=True, help_text='The role the practitioner intends to hold at this org.', max_length=100, null=True)),
                ('requested_department', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the practitioner to the org admin.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled by Requester')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to practitioner on rejection.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'org_membership_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='practitioner',
            name='birth_date',
            field=models.DateField(blank=True, help_text='FHIR: Practitioner.birthDate', null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='gender',
            field=models.CharField(blank=True, help_text='FHIR AdministrativeGender: male | female | other | unknown', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='license_expires_at',
            field=models.DateField(blank=True, help_text='Licence expiry date. Null if licence is permanent.', null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='license_issuing_authority',
            field=models.CharField(blank=True, help_text='e.g. Medical Council of India, GMC, AHPRA.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='qualification',
            field=models.TextField(blank=True, help_text='Freetext qualifications e.g. MBBS, MD, FRCS.', null=True),
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The org admin who approved the membership request.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_practitioner_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='department',
            field=models.CharField(blank=True, help_text="e.g. 'Cardiology', 'Emergency', 'Radiology'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text='Org admin privileges at this organisation. Can approve membership requests and update org details.'),
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary affiliation. Used in visit access checks.'),
        ),
        migrations.AddField(
            model_name='practitionerrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="True once an org admin has approved this practitioner's membership. Required for provider_verified medical events."),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='verification_source',
            field=models.CharField(choices=[('org_admin', 'Verified by Org Admin'), ('registry', 'National Registry Lookup'), ('national_gateway', 'National Health Gateway'), ('self_reported', 'Self-Reported (Unverified)')], default='self_reported', max_length=20),
        ),
        migrations.AddIndex(
            model_name='practitioner',
            index=models.Index(fields=['is_active'], name='idx_prac_active'),
        ),
        migrations.AddIndex(
            model_name='practitionerrole',
            index=models.Index(fields=['organisation', 'is_org_admin', 'is_active'], name='idx_prac_role_org_admin'),
        ),
        migrations.AddConstraint(
            model_name='practitionerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('practitioner', 'organisation'), name='uq_prac_role_active_per_org'),
        ),
        migrations.AddConstraint(
            model_name='practitionerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('practitioner', 'is_primary'), name='uq_prac_role_one_primary'),
        ),
        migrations.AddField(
            model_name='orgmembershiprequest',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_requests', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='orgmembershiprequest',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_requests', to='practitioners.practitioner'),
        ),
        migrations.AddField(
            model_name='orgmembershiprequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, help_text='The org admin who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_membership_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgmembershiprequest',
            name='resulting_role',
            field=models.OneToOneField(blank=True, help_text='The PractitionerRole created when this request was approved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_request', to='practitioners.practitionerrole'),
        ),
        migrations.AddIndex(
            model_name='orgmembershiprequest',
            index=models.Index(fields=['organisation', 'status'], name='idx_membership_req_org_status'),
        ),
        migrations.AddIndex(
            model_name='orgmembershiprequest',
            index=models.Index(fields=['practitioner', 'status'], name='idx_membership_req_prac_status'),
        ),
        migrations.AddConstraint(
            model_name='orgmembershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('practitioner', 'organisation'), name='uq_membership_req_one_pending'),
        ),
    ]
