# Generated by Django 6.0.2 on 2026-04-05 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_accessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='URL-safe random token. Never reused. Included in the share URL.', max_length=64, unique=True)),
                ('validator_type', models.CharField(choices=[('year_of_birth', 'Year of Birth'), ('pin', '4–6 Digit PIN')], help_text='What the doctor must provide to pass the challenge.', max_length=20)),
                ('validator_hash', models.CharField(help_text='bcrypt hash of the raw validator (year of birth as string, or PIN). Never store the raw value.', max_length=128)),
                ('scope', models.CharField(choices=[('timeline_with_opinion', 'Read Timeline + Submit Second Opinion')], default='timeline_with_opinion', max_length=32)),
                ('expires_at', models.DateTimeField(help_text='When this share link expires. After this, verification will fail.')),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('first_accessed_at', models.DateTimeField(blank=True, help_text='Timestamp of first successful verification. Null if never used.', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of successful verifications against this link.')),
                ('label', models.CharField(blank=True, help_text="Optional patient-assigned label e.g. 'For Dr Ahmed at Apollo'.", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The user who generated this share link (must have manage access).', on_delete=django.db.models.deletion.PROTECT, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_links', to='patients.patient')),
            ],
            options={
                'db_table': 'share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLinkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(help_text='Short-lived session credential returned after verification.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='share.sharelink')),
            ],
            options={
                'db_table': 'share_link_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='idx_share_link_token'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['patient', 'is_revoked'], name='idx_share_link_patient'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['expires_at'], name='idx_share_link_expiry'),
        ),
        migrations.AddIndex(
            model_name='sharelinksession',
            index=models.Index(fields=['session_token'], name='idx_share_session_token'),
        ),
        migrations.AddIndex(
            model_name='sharelinksession',
            index=models.Index(fields=['share_link', 'is_revoked'], name='idx_share_session_link'),
        ),
    ]
