# Generated by Django 6.0.2 on 2026-04-09 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_events', '0001_initial'),
        ('organisations', '0002_organisation_description_organisation_parent_and_more'),
        ('patients', '0004_accessrequest'),
        ('practitioners', '0002_orgmembershiprequest_practitioner_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text="Human-readable test name. e.g. 'Complete Blood Count', 'Chest X-Ray'.", max_length=255)),
                ('category', models.CharField(choices=[('laboratory', 'Laboratory / Pathology'), ('imaging', 'Imaging / Radiology'), ('cardiology', 'Cardiology (ECG, Echo, Stress)'), ('pulmonology', 'Pulmonology (PFT, Sleep Study)'), ('neurology', 'Neurology (EEG, NCS)'), ('microbiology', 'Microbiology / Culture'), ('histology', 'Histology / Biopsy'), ('specialist', 'Specialist Consultation'), ('other', 'Other')], default='laboratory', max_length=20)),
                ('coding_system', models.CharField(blank=True, help_text="'http://loinc.org' or 'http://snomed.info/sct'", max_length=100, null=True)),
                ('coding_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coding_display', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent (same day)'), ('stat', 'STAT (immediate)'), ('asap', 'ASAP (as soon as possible)')], default='routine', max_length=10)),
                ('clinical_reason', models.TextField(help_text='Why this test is being ordered. Shown to patient and lab.')),
                ('special_instructions', models.TextField(blank=True, help_text="e.g. 'Fasting required', 'Collect at 8am', 'Use pediatric tube'.", null=True)),
                ('specimen_type', models.CharField(blank=True, help_text="e.g. 'Venous blood', 'Mid-stream urine', 'Nasopharyngeal swab'.", max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (not yet submitted)'), ('active', 'Active (submitted, awaiting collection)'), ('specimen_collected', 'Specimen Collected'), ('in_lab', 'In Lab (processing)'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', max_length=25)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, help_text='When the test should be completed by.', null=True)),
                ('specimen_collected_at', models.DateTimeField(blank=True, null=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cpoe_order_id', models.CharField(blank=True, help_text='# CPOE — External order ID', max_length=256, null=True)),
                ('order_set_id', models.UUIDField(blank=True, help_text='# CPOE — Parent order set UUID', null=True)),
                ('billing_code', models.CharField(blank=True, help_text='# CPOE — CPT or local billing code', max_length=20, null=True)),
                ('lab_interface_code', models.CharField(blank=True, help_text='# CPOE — HL7 OBR-4 universal service ID', max_length=100, null=True)),
                ('destination_lab', models.CharField(blank=True, help_text='# CPOE — Where the order is routed', max_length=255, null=True)),
                ('requires_auth', models.BooleanField(default=False, help_text='# CPOE — Insurance pre-auth required')),
                ('auth_reference', models.CharField(blank=True, help_text='# CPOE — Insurance authorisation reference', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_orders_created', to=settings.AUTH_USER_MODEL)),
                ('ordering_organisation', models.ForeignKey(blank=True, help_text='The organisation context in which this order was placed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_orders', to='organisations.organisation')),
                ('ordering_practitioner', models.ForeignKey(help_text='The practitioner who ordered this test.', on_delete=django.db.models.deletion.PROTECT, related_name='test_orders_placed', to='practitioners.practitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_orders', to='patients.patient')),
                ('resulting_event', models.OneToOneField(blank=True, help_text='The ObservationEvent created when this order resulted. Null until the result is received.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_order', to='medical_events.medicalevent')),
            ],
            options={
                'db_table': 'test_orders',
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_order_patient_status'), models.Index(fields=['ordering_practitioner', 'status'], name='idx_order_prac_status'), models.Index(fields=['ordering_organisation', 'status'], name='idx_order_org_status'), models.Index(fields=['cpoe_order_id'], name='idx_order_cpoe_id'), models.Index(fields=['order_set_id'], name='idx_order_set')],
            },
        ),
    ]
