# Generated by Django 6.0.2 on 2026-02-17 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('activation', 'Activation'), ('reset', 'Password Reset')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='users_usert_token_95b671_idx'), models.Index(fields=['user', 'token_type'], name='users_usert_user_id_456b80_idx'), models.Index(fields=['expires_at'], name='users_usert_expires_9d6b91_idx')],
            },
        ),
    ]
