# Generated by Django 6.0.2 on 2026-02-17 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertoken'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usertoken',
            name='users_usert_token_95b671_idx',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='token_hash',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token_type',
            field=models.CharField(choices=[('activation', 'Activation'), ('password_reset', 'Password Reset')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='is_revoked',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='token',
        ),
    ]
