# Generated by Django 6.0.2 on 2026-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usertoken_users_usert_token_95b671_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
