# Generated by Django 6.0.2 on 2026-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertoken_is_revoked_usertoken_revoked_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usertoken',
            name='users_usert_user_id_456b80_idx',
        ),
        migrations.RemoveIndex(
            model_name='usertoken',
            name='users_usert_expires_9d6b91_idx',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token_type',
            field=models.CharField(choices=[('activation', 'Activation'), ('password_reset', 'Password Reset')], max_length=30),
        ),
    ]
