# Generated by Django 6.0.2 on 2026-02-19 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClaimOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(help_text='Hashed OTP (bcrypt or SHA-256). Raw OTP is never stored.', max_length=256)),
                ('sent_to_email_masked', models.CharField(help_text='Masked version of the patient profile email the OTP was sent to. Audit use only.', max_length=256)),
                ('expires_at', models.DateTimeField(help_text='OTP is valid for 10 minutes from creation.')),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_invalidated', models.BooleanField(default=False)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, help_text="Why this OTP was invalidated (e.g. 'max_attempts', 'superseded').", max_length=64, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts made. Max 3 before force-invalidation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile_claim_otps',
            },
        ),
        migrations.CreateModel(
            name='SupportClaimRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text="The requester's explanation of why they are claiming this profile.")),
                ('submitted_document_refs', models.JSONField(blank=True, default=list, help_text='Storage references to uploaded identity documents. Not the documents themselves.')),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Agent Review'), ('in_review', 'In Review — Assigned to Agent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Requester')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text="Agent's written justification. Mandatory on approval or rejection.", null=True)),
                ('dispute_window_expires_at', models.DateTimeField(blank=True, help_text='14-day window for the current delegate to dispute an approved claim.', null=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_claim_requests',
            },
        ),
        migrations.CreateModel(
            name='ClaimAttemptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('national_id', 'Tier 1 — National ID Match'), ('email_otp', 'Tier 2 — Email OTP'), ('support', 'Tier 3 — Support Manual')], max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed (Wrong OTP / No Match)'), ('expired', 'Expired (OTP or Session Timeout)'), ('rate_limited', 'Rate Limited'), ('blocked', 'Blocked (Too Many Attempts)')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, help_text="Machine-readable failure detail (e.g. 'otp_expired', 'max_attempts_exceeded').", max_length=128, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_attempt_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_attempt_logs',
            },
        ),
    ]
