# Generated by Django 6.0.2 on 2026-02-19 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('integrations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimattemptlog',
            name='external_identity',
            field=models.ForeignKey(blank=True, help_text='Populated for Tier 1 attempts (national ID match).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_logs', to='integrations.externalpatientidentity'),
        ),
        migrations.AddField(
            model_name='claimattemptlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_attempt_logs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='profileclaimotp',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_otps', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='profileclaimotp',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_otps_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimattemptlog',
            name='otp_record',
            field=models.ForeignKey(blank=True, help_text='Populated for Tier 2 attempts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_logs', to='claims.profileclaimotp'),
        ),
        migrations.AddField(
            model_name='supportclaimrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_claim_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportclaimrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_claim_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='supportclaimrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_claim_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportclaimrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_claim_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimattemptlog',
            name='support_request',
            field=models.ForeignKey(blank=True, help_text='Populated for Tier 3 attempts.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_logs', to='claims.supportclaimrequest'),
        ),
        migrations.AddIndex(
            model_name='profileclaimotp',
            index=models.Index(fields=['patient', 'created_at'], name='idx_claimotp_patient_created'),
        ),
        migrations.AddIndex(
            model_name='profileclaimotp',
            index=models.Index(fields=['patient', 'requested_by', 'is_used', 'is_invalidated'], name='idx_claimotp_active'),
        ),
        migrations.AddIndex(
            model_name='supportclaimrequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_scr_status_created'),
        ),
        migrations.AddIndex(
            model_name='supportclaimrequest',
            index=models.Index(fields=['patient', 'status'], name='idx_scr_patient_status'),
        ),
        migrations.AddIndex(
            model_name='claimattemptlog',
            index=models.Index(fields=['patient', 'attempted_at'], name='idx_cal_patient_time'),
        ),
        migrations.AddIndex(
            model_name='claimattemptlog',
            index=models.Index(fields=['ip_address', 'attempted_at'], name='idx_cal_ip_time'),
        ),
        migrations.AddIndex(
            model_name='claimattemptlog',
            index=models.Index(fields=['attempted_by', 'attempted_at'], name='idx_cal_user_time'),
        ),
    ]
