# Generated by Django 6.0.2 on 2026-02-19 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrn', models.CharField(blank=True, help_text='UHR-internal Medical Record Number. National / external IDs belong in integrations.ExternalPatientIdentity.', max_length=64, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g. IN, AU, GB, DE, US).', max_length=2, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('deceased_date', models.DateField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False, help_text='True once the real patient has proven their identity and holds role=primary in PatientUserAccess.')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_eligible_at', models.DateField(blank=True, help_text="Date from which the patient may independently claim this profile. For minor profiles: set to the patient's 18th birthday at creation. DateField (not DateTime) — eligibility is calendar-date based, not time-of-day precise. Compare against date.today() in service layer. System surfaces a transfer prompt to both parties on this date.", null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('retraction_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['birth_date'], name='idx_patient_birth_date'), models.Index(fields=['deleted_at'], name='idx_patient_deleted_at'), models.Index(fields=['nationality'], name='idx_patient_nationality'), models.Index(fields=['is_claimed'], name='idx_patient_is_claimed'), models.Index(fields=['transfer_eligible_at'], name='idx_patient_transfer_eligible'), models.Index(condition=models.Q(('email__isnull', False)), fields=['email'], name='idx_patient_email')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_deceased', False), models.Q(('deceased_date__isnull', False), ('is_deceased', True)), _connector='OR'), name='chk_patient_deceased_consistency')],
            },
        ),
        migrations.CreateModel(
            name='PatientUserAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary (Patient — Identity Verified)'), ('full_delegate', 'Full Delegate (Guardian / Pre-Claim)'), ('caregiver', 'Caregiver (Read + Write)'), ('viewer', 'Viewer (Read Only)')], default='full_delegate', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False on revocation. Never delete this record.')),
                ('claim_method', models.CharField(choices=[('national_id_match', 'Tier 1 — National ID Match (Automated)'), ('email_otp', 'Tier 2 — Email OTP (Automated)'), ('support_manual', 'Tier 3 — Support-Assisted Manual Verification'), ('delegate_transfer', 'Delegate-Initiated Transfer (Invitation)'), ('system_created', 'System Created (Profile Creation)')], default='system_created', help_text='How this access was established. Set once. Never changed.', max_length=32)),
                ('trust_level', models.CharField(choices=[('verified_identity', 'Verified Identity (National ID)'), ('email_verified', 'Email Verified (OTP)'), ('support_verified', 'Support Verified (Manual)'), ('delegate_granted', 'Delegate Granted (No independent verification)'), ('system', 'System (Auto-created, pre-claim)')], default='system', help_text='Confidence level of the establishing claim. Set once. Never changed.', max_length=32)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_identity', models.ForeignKey(blank=True, help_text='Tier 1: the ExternalPatientIdentity match that proved this claim.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_claims', to='integrations.externalpatientidentity')),
                ('claim_otp', models.ForeignKey(blank=True, help_text='Tier 2: the ProfileClaimOTP record that verified this claim.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_claims', to='claims.profileclaimotp')),
                ('claim_ticket', models.ForeignKey(blank=True, help_text='Tier 3: the SupportClaimRequest that authorised this claim.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_claims', to='claims.supportclaimrequest')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Who granted this access. Null for claim-initiated or self-created.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='granted_patient_accesses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='patients.patient')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_patient_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_user_access',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_pua_user_active'), models.Index(fields=['patient', 'is_active'], name='idx_pua_patient_active'), models.Index(fields=['patient', 'role', 'is_active'], name='idx_pua_patient_role')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'patient'), name='uq_pua_user_patient_active'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'primary')), fields=('patient', 'role'), name='uq_pua_one_primary_per_patient'), models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='chk_pua_revocation_consistency')],
            },
        ),
    ]
