# Generated by Django 6.0.2 on 2026-02-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('merge_patient', 'Can merge duplicate patient profiles')]},
        ),
    ]
