# Generated by Django 6.0.2 on 2026-02-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuseraccess',
            name='trust_level',
            field=models.CharField(choices=[('verified_identity', 'Verified Identity (National ID)'), ('email_verified', 'Email Verified (OTP)'), ('support_verified', 'Support Verified (Manual)'), ('delegate_granted', 'Delegate Granted (No independent verification)'), ('system', 'System (Auto-created, pre-claim)'), ('unverified', 'Unverified (Self-asserted, no independent verification)')], default='system', help_text='Confidence level of the establishing claim. Set once. Never changed.', max_length=32),
        ),
    ]
