# Generated by Django 6.0.2 on 2026-04-05 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientuseraccess_trust_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_role', models.CharField(choices=[('caregiver', 'Caregiver (Read + Write)'), ('viewer', 'Viewer (Read Only)')], max_length=20)),
                ('reason', models.TextField(help_text='Why this user needs access. Shown to the patient.')),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting patient response)'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired (patient did not respond)'), ('cancelled', 'Cancelled (requester withdrew)'), ('revoked', 'Revoked (patient revoked after approval)')], default='pending', max_length=20)),
                ('is_permanent', models.BooleanField(default=False, help_text='If True, approved access has no expiry. If False, access_duration_days determines expiry.')),
                ('access_duration_days', models.PositiveIntegerField(blank=True, help_text='How many days access should last after approval. Null if is_permanent=True.', null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='Set at approval time. Null for permanent access.', null=True)),
                ('request_expires_at', models.DateTimeField(help_text='When this request expires if the patient does not respond.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, help_text='Optional reason shown to requester on denial.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_access_requests', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, help_text='The user who approved or denied this request (usually the patient).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responded_access_requests', to=settings.AUTH_USER_MODEL)),
                ('resulting_access', models.OneToOneField(blank=True, help_text='The PatientUserAccess record created when this request was approved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_request', to='patients.patientuseraccess')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_access_request_patient_status'), models.Index(fields=['requested_by', 'status'], name='idx_access_request_requester_status'), models.Index(fields=['status', 'request_expires_at'], name='idx_access_request_expiry')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('patient', 'requested_by'), name='uq_access_request_one_pending_per_user_patient'), models.CheckConstraint(condition=models.Q(('is_permanent', True), models.Q(('access_duration_days__isnull', False), ('is_permanent', False)), _connector='OR'), name='chk_access_request_duration_consistency')],
            },
        ),
    ]
