# Generated by Django 6.0.2 on 2026-04-07 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_organisation_description_organisation_parent_and_more'),
        ('patients', '0004_accessrequest'),
        ('practitioners', '0002_orgmembershiprequest_practitioner_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('visit', 'Visit / Encounter'), ('observation', 'Observation / Lab Result'), ('condition', 'Condition / Diagnosis'), ('medication', 'Medication'), ('procedure', 'Procedure / Surgery'), ('document', 'Document / Report'), ('second_opinion', 'Second Opinion')], max_length=20)),
                ('clinical_timestamp', models.DateTimeField(help_text='When this event occurred in real life. Must be timezone-aware. Used for timeline ordering.')),
                ('system_timestamp', models.DateTimeField(auto_now_add=True, help_text='When this event was recorded in UHR. Set once. Never changed.')),
                ('source_type', models.CharField(choices=[('patient', 'Patient (Self-entered or uploaded)'), ('doctor', 'Doctor / Practitioner'), ('lab', 'Laboratory (Digital integration)'), ('system', 'System (Auto-generated)')], help_text='Who or what created this event.', max_length=10)),
                ('verification_level', models.CharField(choices=[('self_reported', 'Self-Reported (Patient manually entered)'), ('patient_confirmed', 'Patient-Confirmed (OCR-extracted, patient approved)'), ('provider_verified', 'Provider-Verified (Authenticated practitioner)'), ('digitally_verified', 'Digitally Verified (Structured digital integration)')], default='self_reported', help_text="Confidence level of this event's clinical content. provider_verified ONLY for authenticated practitioner submissions.", max_length=20)),
                ('visibility_status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden by Patient'), ('pending_approval', 'Pending Patient Approval')], default='visible', max_length=20)),
                ('amendment_reason', models.TextField(blank=True, help_text="Mandatory when amending. Explains why the correction was made. e.g. 'Typographical error in dosage', 'Updated clinical evidence'.", null=True)),
                ('relationship_type', models.CharField(choices=[('none', 'No relationship'), ('amendment', 'Amends a previous event (correction)'), ('lifecycle', 'Lifecycle transition (e.g. medication modified/stopped)'), ('related', 'Clinically related event')], default='none', max_length=10)),
                ('external_system', models.CharField(blank=True, max_length=100, null=True)),
                ('external_resource_id', models.CharField(blank=True, max_length=256, null=True)),
                ('fhir_resource_type', models.CharField(blank=True, max_length=64, null=True)),
                ('fhir_logical_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amends_event', models.ForeignKey(blank=True, help_text='The event this one corrects. Required when relationship_type=amendment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='medical_events.medicalevent')),
                ('created_by', models.ForeignKey(help_text='The user account that submitted this event.', on_delete=django.db.models.deletion.PROTECT, related_name='created_medical_events', to=settings.AUTH_USER_MODEL)),
                ('parent_event', models.ForeignKey(blank=True, help_text='The medication event this lifecycle transition references.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='medical_events.medicalevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_events', to='patients.patient')),
                ('source_organisation', models.ForeignKey(blank=True, help_text='The organisation context in which this event was created.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sourced_events', to='organisations.organisation')),
                ('source_practitioner', models.ForeignKey(blank=True, help_text='Populated when source_type=doctor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_events', to='practitioners.practitioner')),
            ],
            options={
                'db_table': 'medical_events',
                'ordering': ['-clinical_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConditionEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='condition_event', serialize=False, to='medical_events.medicalevent')),
                ('coding_system', models.CharField(blank=True, max_length=100, null=True)),
                ('coding_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coding_display', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_name', models.CharField(help_text='Human-readable diagnosis name. Always required.', max_length=255)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('recurrence', 'Recurrence'), ('relapse', 'Relapse'), ('inactive', 'Inactive'), ('remission', 'Remission'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('abatement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condition_events',
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='document_event', serialize=False, to='medical_events.medicalevent')),
                ('file_url', models.TextField(help_text='S3 URL or presigned URL to the stored file.')),
                ('file_type', models.CharField(help_text="MIME type e.g. 'application/pdf', 'image/jpeg'.", max_length=20)),
                ('document_type', models.CharField(default='other', help_text='lab_report | prescription | imaging | discharge_summary | referral | vaccination | insurance | other', max_length=30)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename as uploaded by the patient.', max_length=255, null=True)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(help_text='SHA-256 hex digest computed at upload time. Validated on every retrieval.', max_length=64)),
                ('storage_provider', models.CharField(default='s3', help_text='s3 | r2 | minio | local', max_length=20)),
                ('s3_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, help_text='S3 object key. Used to generate presigned URLs on demand.', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'document_events',
            },
        ),
        migrations.CreateModel(
            name='ProcedureEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='procedure_event', serialize=False, to='medical_events.medicalevent')),
                ('coding_system', models.CharField(blank=True, max_length=100, null=True)),
                ('coding_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coding_display', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_name', models.CharField(help_text='Human-readable procedure name. Always required.', max_length=255)),
                ('performed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'procedure_events',
            },
        ),
        migrations.CreateModel(
            name='SecondOpinionEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='second_opinion_event', serialize=False, to='medical_events.medicalevent')),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_registration_number', models.CharField(blank=True, help_text='Optional — not required for anonymous share-link submissions.', max_length=100, null=True)),
                ('opinion_text', models.TextField()),
                ('approved_by_patient', models.BooleanField(default=False, help_text='True once the patient has reviewed and approved this opinion. Unapproved opinions are excluded from doctor-facing timeline views.')),
            ],
            options={
                'db_table': 'second_opinion_events',
            },
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='visit_event', serialize=False, to='medical_events.medicalevent')),
                ('reason', models.TextField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, help_text='e.g. outpatient, inpatient, emergency, telehealth', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visit_events',
            },
        ),
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='medication_event', serialize=False, to='medical_events.medicalevent')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, help_text="e.g. '500mg'", max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, help_text="e.g. 'twice daily', 'every 8 hours'", max_length=100, null=True)),
                ('route', models.CharField(blank=True, help_text="e.g. 'oral', 'intravenous', 'topical'", max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed (course finished)'), ('discontinued', 'Discontinued'), ('on_hold', 'On Hold'), ('unknown', 'Unknown')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_events',
                'indexes': [models.Index(fields=['status'], name='idx_med_status')],
            },
        ),
        migrations.CreateModel(
            name='ObservationEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='observation_event', serialize=False, to='medical_events.medicalevent')),
                ('coding_system', models.CharField(blank=True, help_text="e.g. 'http://loinc.org'", max_length=100, null=True)),
                ('coding_code', models.CharField(blank=True, help_text="e.g. '2345-7' (LOINC for blood glucose)", max_length=50, null=True)),
                ('coding_display', models.CharField(blank=True, help_text="Human-readable name e.g. 'Glucose [Mass/volume] in Blood'", max_length=255, null=True)),
                ('observation_name', models.CharField(help_text='Human-readable test name. Always required.', max_length=255)),
                ('value_type', models.CharField(default='quantity', help_text='quantity | string | boolean', max_length=10)),
                ('value_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_unit', models.CharField(blank=True, help_text="e.g. 'mg/dL', 'mmol/L', 'bpm'", max_length=50, null=True)),
                ('value_string', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_range', models.CharField(blank=True, help_text="e.g. '70-100 mg/dL'", max_length=100, null=True)),
            ],
            options={
                'db_table': 'observation_events',
                'indexes': [models.Index(fields=['coding_code'], name='idx_obs_coding_code')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['patient', 'clinical_timestamp'], name='idx_me_patient_clinical_ts'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['event_type'], name='idx_me_event_type'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['source_practitioner'], name='idx_me_source_prac'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['visibility_status'], name='idx_me_visibility'),
        ),
        migrations.AddIndex(
            model_name='medicalevent',
            index=models.Index(fields=['external_resource_id'], name='idx_me_ext_resource'),
        ),
        migrations.AddConstraint(
            model_name='medicalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amends_event__isnull', False), ('relationship_type', 'amendment')), models.Q(('relationship_type', 'amendment'), _negated=True), _connector='OR'), name='chk_me_amendment_requires_amends_event'),
        ),
        migrations.AddConstraint(
            model_name='medicalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_event__isnull', False), ('relationship_type', 'lifecycle')), models.Q(('relationship_type', 'lifecycle'), _negated=True), _connector='OR'), name='chk_me_lifecycle_requires_parent_event'),
        ),
    ]
