# Generated by Django 6.0.2 on 2026-04-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_events', '0001_initial'),
        ('practitioners', '0002_orgmembershiprequest_practitioner_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSignsEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='vital_signs_event', serialize=False, to='medical_events.medicalevent')),
                ('systolic_bp', models.DecimalField(blank=True, decimal_places=1, help_text='mmHg — LOINC 8480-6', max_digits=6, null=True)),
                ('diastolic_bp', models.DecimalField(blank=True, decimal_places=1, help_text='mmHg — LOINC 8462-4', max_digits=6, null=True)),
                ('bp_position', models.CharField(blank=True, help_text='sitting | standing | lying', max_length=20, null=True)),
                ('heart_rate', models.DecimalField(blank=True, decimal_places=1, help_text='bpm', max_digits=6, null=True)),
                ('heart_rhythm', models.CharField(blank=True, help_text='regular | irregular', max_length=50, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=5, null=True)),
                ('temp_site', models.CharField(blank=True, help_text='oral | axillary | tympanic | rectal', max_length=20, null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('on_oxygen', models.BooleanField(blank=True, help_text='Whether patient is on supplemental oxygen.', null=True)),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=1, help_text='breaths/min', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-computed if weight+height provided.', max_digits=5, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, help_text='0–10 numeric pain scale.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vital_signs_events',
            },
        ),
        migrations.AlterField(
            model_name='medicalevent',
            name='event_type',
            field=models.CharField(choices=[('visit', 'Visit / Encounter'), ('observation', 'Observation / Lab Result'), ('condition', 'Condition / Diagnosis'), ('medication', 'Medication'), ('procedure', 'Procedure / Surgery'), ('document', 'Document / Report'), ('second_opinion', 'Second Opinion'), ('allergy', 'Allergy / Intolerance'), ('vaccination', 'Vaccination / Immunization'), ('consultation', 'Consultation'), ('vital_signs', 'Vital Signs')], max_length=20),
        ),
        migrations.CreateModel(
            name='AllergyEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='allergy_event', serialize=False, to='medical_events.medicalevent')),
                ('substance_name', models.CharField(help_text='Free-text substance name. Always required.', max_length=255)),
                ('coding_system', models.CharField(blank=True, help_text="e.g. 'http://snomed.info/sct'", max_length=100, null=True)),
                ('coding_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coding_display', models.CharField(blank=True, max_length=255, null=True)),
                ('allergy_type', models.CharField(choices=[('allergy', 'Allergy'), ('intolerance', 'Intolerance')], default='allergy', max_length=20)),
                ('category', models.CharField(choices=[('food', 'Food'), ('medication', 'Medication'), ('environment', 'Environment'), ('biologic', 'Biologic'), ('other', 'Other')], default='medication', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Low risk'), ('high', 'High risk (life-threatening)'), ('unable_to_assess', 'Unable to assess')], default='unable_to_assess', max_length=20)),
                ('reaction_type', models.CharField(blank=True, help_text="e.g. 'anaphylaxis', 'urticaria', 'nausea', 'angioedema'", max_length=200, null=True)),
                ('reaction_severity', models.CharField(blank=True, help_text='mild | moderate | severe', max_length=20, null=True)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('entered_in_error', 'Entered in Error')], default='active', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'allergy_events',
                'indexes': [models.Index(fields=['clinical_status'], name='idx_allergy_status'), models.Index(fields=['criticality'], name='idx_allergy_criticality'), models.Index(fields=['category'], name='idx_allergy_category')],
            },
        ),
        migrations.CreateModel(
            name='VaccinationEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='vaccination_event', serialize=False, to='medical_events.medicalevent')),
                ('vaccine_name', models.CharField(help_text="e.g. 'COVID-19 mRNA (Pfizer-BioNTech)'", max_length=255)),
                ('coding_system', models.CharField(blank=True, help_text="CVX system: 'http://hl7.org/fhir/sid/cvx'", max_length=100, null=True)),
                ('coding_code', models.CharField(blank=True, help_text="CVX code e.g. '208' for Pfizer COVID-19", max_length=50, null=True)),
                ('coding_display', models.CharField(blank=True, max_length=255, null=True)),
                ('dose_number', models.CharField(blank=True, help_text="e.g. '1', '2', 'Booster'", max_length=20, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('next_dose_due_date', models.DateField(blank=True, null=True)),
                ('administering_org', models.CharField(blank=True, help_text='Hospital or clinic where administered.', max_length=255, null=True)),
                ('site', models.CharField(blank=True, help_text="e.g. 'Left arm', 'Right deltoid'", max_length=100, null=True)),
                ('route', models.CharField(blank=True, help_text="e.g. 'Intramuscular', 'Subcutaneous'", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaccination_events',
                'indexes': [models.Index(fields=['coding_code'], name='idx_vacc_coding_code')],
            },
        ),
        migrations.CreateModel(
            name='ConsultationEvent',
            fields=[
                ('medical_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='consultation_event', serialize=False, to='medical_events.medicalevent')),
                ('department', models.CharField(choices=[('general_practice', 'General Practice / Family Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopaedics', 'Orthopaedics'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology / Respiratory'), ('nephrology', 'Nephrology'), ('endocrinology', 'Endocrinology / Diabetes'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry / Mental Health'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('urology', 'Urology'), ('gynaecology', 'Gynaecology & Obstetrics'), ('paediatrics', 'Paediatrics'), ('haematology', 'Haematology'), ('radiology', 'Radiology'), ('rheumatology', 'Rheumatology'), ('emergency', 'Emergency Medicine'), ('other', 'Other')], default='general_practice', help_text='The clinical department this consultation belongs to.', max_length=30)),
                ('sub_specialty', models.CharField(blank=True, help_text="Further specialization e.g. 'Interventional Cardiology', 'Epilepsy'.", max_length=100, null=True)),
                ('chief_complaint', models.TextField(help_text='Why the patient presented. Always required.')),
                ('history_of_present_illness', models.TextField(blank=True, help_text='Relevant history leading up to this consultation.', null=True)),
                ('examination_findings', models.TextField(blank=True, help_text='Physical examination findings.', null=True)),
                ('investigations_ordered', models.TextField(blank=True, help_text='Tests or investigations ordered during this consultation.', null=True)),
                ('assessment', models.TextField(blank=True, help_text='Clinical assessment / impression.', null=True)),
                ('plan', models.TextField(blank=True, help_text='Management plan agreed during the consultation.', null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True, null=True)),
                ('consulting_practitioner', models.ForeignKey(blank=True, help_text='The practitioner who conducted this consultation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_events', to='practitioners.practitioner')),
                ('referred_by', models.ForeignKey(blank=True, help_text='The practitioner who referred the patient for this consultation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_consultation_events', to='practitioners.practitioner')),
            ],
            options={
                'db_table': 'consultation_events',
                'indexes': [models.Index(fields=['department'], name='idx_consult_dept'), models.Index(fields=['consulting_practitioner'], name='idx_consult_prac')],
            },
        ),
    ]
