# Generated by Django 6.0.2 on 2026-04-05 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('patients', '0004_accessrequest'),
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this visit session automatically expires.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Explicit end time. Null if visit expired naturally.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False once ended or expired.')),
                ('visit_reason', models.CharField(blank=True, help_text="Optional reason for visit e.g. 'Annual checkup', 'Follow-up'.", max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_visits', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_visits', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visits', to='organisations.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_visits',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisitAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_accessed_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="False if this practitioner's access was revoked mid-visit.")),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_accesses', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visit_accesses', to='practitioners.practitioner')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_visit_accesses', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_accesses', to='visits.patientvisit')),
            ],
            options={
                'db_table': 'patient_visit_accesses',
            },
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['patient', 'organisation', 'is_active'], name='idx_visit_patient_org_active'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['patient', 'initiated_at'], name='idx_visit_patient_history'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['is_active', 'expires_at'], name='idx_visit_active_expiry'),
        ),
        migrations.AddIndex(
            model_name='patientvisitaccess',
            index=models.Index(fields=['visit', 'practitioner'], name='idx_visit_access_visit_prac'),
        ),
        migrations.AddIndex(
            model_name='patientvisitaccess',
            index=models.Index(fields=['patient', 'first_accessed_at'], name='idx_visit_access_patient'),
        ),
        migrations.AddConstraint(
            model_name='patientvisitaccess',
            constraint=models.UniqueConstraint(fields=('visit', 'practitioner'), name='uq_visit_access_visit_practitioner'),
        ),
    ]
