# Generated by Django 6.0.2 on 2026-04-09 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_description_organisation_parent_and_more'),
        ('patients', '0004_accessrequest'),
        ('practitioners', '0002_orgmembershiprequest_practitioner_birth_date_and_more'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='access_scope',
            field=models.CharField(default='stats_only', help_text='stats_only (default): health stats, allergies, active meds, conditions. full_timeline: patient approved full record access for this visit.', max_length=20),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='scope',
            field=models.CharField(choices=[('stats_only', 'Stats Only (Triage — auto-granted)'), ('full_timeline', 'Full Timeline (requires patient approval)')], default='stats_only', help_text='What data this organisation can access. stats_only is auto-granted. full_timeline requires patient approval.', max_length=20),
        ),
        migrations.CreateModel(
            name='VisitConsentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_scope', models.CharField(choices=[('clinical_summary', 'Clinical Summary (Tier 1 — auto)'), ('full_timeline', 'Full Timeline (Tier 2 — consent required)'), ('date_range', 'Date Range (Tier 2 — scoped consent)')], default='full_timeline', max_length=20)),
                ('date_range_from', models.DateField(blank=True, help_text='Start of date range for date_range scope.', null=True)),
                ('date_range_to', models.DateField(blank=True, help_text='End of date range for date_range scope.', null=True)),
                ('reason', models.TextField(help_text='Why full access is needed. Shown to patient.')),
                ('status', models.CharField(choices=[('pending', 'Pending Patient Response'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked by Patient'), ('expired', 'Expired (visit ended)')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-set to visit.expires_at when approved.', null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('fhir_export_enabled', models.BooleanField(default=False, help_text="Tier 3 EHR hook. When True, a FHIR Bundle is available for import into the organisation's EHR system.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_consent_requests', to='organisations.organisation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_consent_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(help_text='The practitioner who requested elevated access.', on_delete=django.db.models.deletion.PROTECT, related_name='consent_requests_made', to='practitioners.practitioner')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_requests', to='visits.patientvisit')),
            ],
            options={
                'db_table': 'visit_consent_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_visit_consent_patient_status'), models.Index(fields=['visit', 'status'], name='idx_visit_consent_visit_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('visit', 'organisation'), name='uq_visit_consent_one_pending')],
            },
        ),
        migrations.CreateModel(
            name='VisitScopeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text="Clinical reason for requesting full timeline access. Shown to the patient. Be specific — e.g. 'Reviewing full cardiac history before procedure' rather than 'Need to see records'.")),
                ('status', models.CharField(choices=[('pending', 'Pending patient approval'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired (patient did not respond)')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, help_text='Optional reason shown to the practitioner on denial.', null=True)),
                ('expires_at', models.DateTimeField(help_text='Request expires if patient does not respond by this time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(help_text='The practitioner requesting full timeline access.', on_delete=django.db.models.deletion.PROTECT, related_name='scope_requests_made', to='practitioners.practitioner')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scope_request_responses', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_requests', to='visits.patientvisit')),
            ],
            options={
                'db_table': 'visit_scope_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit', 'status'], name='idx_scope_req_visit_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('visit', 'requested_by'), name='uq_scope_req_one_pending_per_prac')],
            },
        ),
        migrations.CreateModel(
            name='VisitTimelineRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why full timeline access is needed for this visit. Shown to the patient when they review the request.')),
                ('status', models.CharField(choices=[('pending', 'Pending (awaiting patient response)'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_timeline_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_requests_made', to='practitioners.practitioner')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_timeline_responses', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_requests', to='visits.patientvisit')),
            ],
            options={
                'db_table': 'visit_timeline_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='idx_visit_tlreq_patient_status'), models.Index(fields=['visit', 'status'], name='idx_visit_tlreq_visit_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('visit',), name='uq_visit_timeline_req_one_pending')],
            },
        ),
    ]
