# Generated by Django 6.0.2 on 2026-04-05 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official registered name of the organisation.', max_length=255)),
                ('type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('lab', 'Diagnostic Laboratory'), ('pharmacy', 'Pharmacy'), ('telehealth', 'Telehealth Provider'), ('other', 'Other')], default='hospital', max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='Official government or health authority registration number.', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g. IN, AU, GB).', max_length=2, null=True)),
                ('verified', models.BooleanField(default=False, help_text='True once verified by UHR admin. Only verified organisations can host active visit sessions.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, help_text='The admin user who verified this organisation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['verified', 'is_active'], name='idx_org_verified_active'), models.Index(fields=['country'], name='idx_org_country'), models.Index(fields=['type'], name='idx_org_type')],
            },
        ),
    ]
