# Generated by Django 6.0.2 on 2026-04-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent organisation for branch hierarchies. Null for standalone.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic / Outpatient Centre'), ('lab', 'Diagnostic Laboratory'), ('pharmacy', 'Pharmacy'), ('telehealth', 'Telehealth Provider'), ('imaging', 'Imaging / Radiology Centre'), ('dental', 'Dental Practice'), ('mental_health', 'Mental Health Centre'), ('other', 'Other')], default='hospital', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='The UHR staff user who verified this organisation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_organisations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['parent'], name='idx_org_parent'),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number__isnull', False)), fields=('registration_number', 'country'), name='uq_org_reg_number_country'),
        ),
    ]
